import os
import base64
import anthropic
import time

client = anthropic.Anthropic()

# Root image directory — scans ALL subdirectories recursively
image_root = r"c:\Projects\SV-Build\images"
output_file = r"c:\Projects\SV-Build\_ai\image-library.md"

# Skip hero mobile and rel thumbnails — not content images
skip_suffixes = ("-mobile.webp", "-rel.webp")

# Supported image types
valid_ext = {".webp", ".jpg", ".jpeg", ".png"}

media_map = {
    ".webp": "image/webp",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png":  "image/png",
}

# Collect all images
all_images = []
for root, dirs, files in os.walk(image_root):
    # Skip hidden folders
    dirs[:] = [d for d in dirs if not d.startswith('.')]
    for fname in sorted(files):
        ext = os.path.splitext(fname)[1].lower()
        if ext not in valid_ext:
            continue
        if any(fname.endswith(s) for s in skip_suffixes):
            continue
        fpath = os.path.join(root, fname)
        rel_path = os.path.relpath(fpath, image_root)
        all_images.append((rel_path, fpath, fname, ext))

print(f"Found {len(all_images)} images to describe")
print(f"Output: {output_file}")
print()

lines = []
lines.append("# SV-Build Full Image Library")
lines.append(f"## {len(all_images)} images described")
lines.append("## Generated by Anti-Gravity — do not edit manually")
lines.append("")
lines.append("| Path | Filename | Size | Description |")
lines.append("|---|---|---|---|")

errors = []

for i, (rel_path, fpath, fname, ext) in enumerate(all_images, 1):
    size = os.path.getsize(fpath)
    folder = os.path.dirname(rel_path)

    try:
        with open(fpath, "rb") as f:
            img_data = base64.standard_b64encode(f.read()).decode("utf-8")

        response = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=120,
            messages=[{
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_map[ext],
                            "data": img_data,
                        },
                    },
                    {
                        "type": "text",
                        "text": "Describe what is physically visible in this image in one plain sentence. Be specific about objects, colours, setting, people and any text visible. No interpretation."
                    }
                ],
            }]
        )

        description = response.content[0].text.strip().replace("|", "-")
        lines.append(f"| {folder} | {fname} | {size:,} | {description} |")
        print(f"[{i}/{len(all_images)}] ✅ {rel_path}")
        print(f"   {description}")

    except Exception as e:
        error_msg = f"ERROR: {str(e)}"
        lines.append(f"| {folder} | {fname} | {size:,} | {error_msg} |")
        errors.append((rel_path, str(e)))
        print(f"[{i}/{len(all_images)}] ❌ {rel_path} — {e}")

    # Save progress every 25 images in case of interruption
    if i % 25 == 0:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        print(f"\n  [Checkpoint saved at {i} images]\n")

    # Small delay to avoid rate limiting
    time.sleep(0.3)

# Final save
os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"\n{'='*60}")
print(f"DONE. {len(all_images)} images described.")
print(f"Errors: {len(errors)}")
for rel, err in errors:
    print(f"  ❌ {rel}: {err}")
print(f"Saved to: {output_file}")
